#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

BIN="sh export NODE_PATH=/root/node_modules; node /usr/bin/smart_light.js"

start_service() {
    procd_open_instance
    procd_set_param command $BIN
    procd_set_param respawn
    procd_close_instance
}
