#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

BIN="sh /etc/init.d/smart_light_script.sh"

start_service() {
    procd_open_instance
    procd_set_param command $BIN
    procd_set_param respawn
    procd_close_instance
}
